config_LAFTR = {
    'adult': {
        'v0':
        {
            'encoder_hdims':None,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : None,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : None,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':None,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v1':{
            'encoder_hdims':[50],
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50],
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50],
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50],
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v2':{
            'encoder_hdims':[50]*2,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*2,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*2,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*2,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v3':{
            'encoder_hdims':[50]*3,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*3,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*3,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*3,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v4':{
            'encoder_hdims':[50],
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50],
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50],
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50],
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v5':{
            'encoder_hdims':[50]*2,
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*2,
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*2,
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*2,
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v6':{
            'encoder_hdims':[50]*3,
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*3,
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*3,
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*3,
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v7':{
            'encoder_hdims':[50],
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50],
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50],
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50],
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v8':{
            'encoder_hdims':[50]*2,
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*2,
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*2,
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*2,
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        },
        'v9':{
            'encoder_hdims':[50]*3,
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*3,
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*3,
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*3,
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 12
        }
            },
    'compas':{
        'v0':
        {
            'encoder_hdims':None,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : None,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : None,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':None,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v1':{
            'encoder_hdims':[50],
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50],
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50],
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50],
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v2':{
            'encoder_hdims':[50]*2,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*2,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*2,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*2,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v3':{
            'encoder_hdims':[50]*3,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*3,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*3,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*3,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v4':{
            'encoder_hdims':[50],
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50],
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50],
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50],
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v5':{
            'encoder_hdims':[50]*2,
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*2,
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*2,
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*2,
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v6':{
            'encoder_hdims':[50]*3,
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*3,
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*3,
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*3,
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v7':{
            'encoder_hdims':[50],
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50],
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50],
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50],
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v8':{
            'encoder_hdims':[50]*2,
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*2,
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*2,
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*2,
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        },
        'v9':{
            'encoder_hdims':[50]*3,
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [50]*3,
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [50]*3,
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[50]*3,
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim':12
        }
            },
    'census_income_kdd':{
        'v0':
        {
            'encoder_hdims':None,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : None,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : None,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':None,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v1':{
            'encoder_hdims':[200],
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200],
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200],
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200],
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v2':{
            'encoder_hdims':[200]*2,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200]*2,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200]*2,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200]*2,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v3':{
            'encoder_hdims':[200]*3,
            'encoder_activation_hidden': None,
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200]*3,
            'decoder_activation_hidden': None,
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200]*3,
            'adversary_activation_hidden': None,
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200]*3,
            'classifier_activation_hidden': None,
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v4':{
            'encoder_hdims':[200],
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200],
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200],
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200],
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v5':{
            'encoder_hdims':[200]*2,
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200]*2,
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200]*2,
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200]*2,
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v6':{
            'encoder_hdims':[200]*3,
            'encoder_activation_hidden': 'relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200]*3,
            'decoder_activation_hidden': 'relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200]*3,
            'adversary_activation_hidden': 'relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200]*3,
            'classifier_activation_hidden': 'relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v7':{
            'encoder_hdims':[200],
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200],
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200],
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200],
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        },
        'v8':{
            'encoder_hdims':[200]*2,
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200]*2,
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200]*2,
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200]*2,
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 200
        },
        'v9':{
            'encoder_hdims':[200]*3,
            'encoder_activation_hidden': 'leaky-relu',
            'encoder_activation_output': None,
            'encoder_p_dropout': None,
            'decoder_hdims' : [200]*3,
            'decoder_activation_hidden': 'leaky-relu',
            'decoder_activation_output': None,
            'decoder_p_dropout': None,
            'adversary_hdims' : [200]*3,
            'adversary_activation_hidden': 'leaky-relu',
            'adversary_activation_output': None,
            'adversary_p_dropout': None,
            'classifier_hdims':[200]*3,
            'classifier_activation_hidden': 'leaky-relu',
            'classifier_activation_output': None,
            'classifier_p_dropout': None,
            'z_dim': 100
        }
    },
}
