config_VFAE = {
    'adult': {
            'v0':{
                'z1_enc_dim':None,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':None,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':None,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':None,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v1':{
                'z1_enc_dim':[50],
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50],
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50],
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50],
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v2':{
                'z1_enc_dim':[50]*2,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*2,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*2,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*2,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v3':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v4':{
                'z1_enc_dim':[50],
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50],
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50],
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50],
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v5':{
                'z1_enc_dim':[50]*2,
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*2,
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*2,
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*2,
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v6':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v7':{
                'z1_enc_dim':[50]*2,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*2,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*2,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*2,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v8':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v9':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            },
    'compas':{
            'v0':{
                'z1_enc_dim':None,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':None,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':None,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':None,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v1':{
                'z1_enc_dim':[50],
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50],
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50],
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50],
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v2':{
                'z1_enc_dim':[50]*2,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*2,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*2,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*2,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v3':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v4':{
                'z1_enc_dim':[50],
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50],
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50],
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50],
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v5':{
                'z1_enc_dim':[50]*2,
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*2,
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*2,
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*2,
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v6':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v7':{
                'z1_enc_dim':[50]*2,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*2,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*2,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*2,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v8':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v9':{
                'z1_enc_dim':[50]*3,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[50]*3,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[50]*3,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[50]*3,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':12,
                'beta':1.0,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            },
    'census_income_kdd':{
            'v0':{
                'z1_enc_dim':None,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':None,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':None,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':None,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v1':{
                'z1_enc_dim':[200],
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200],
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200],
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200],
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v2':{
                'z1_enc_dim':[200]*2,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200]*2,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200]*2,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200]*2,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v3':{
                'z1_enc_dim':[200]*3,
                'z1_enc_activation_hidden': None,
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200]*3,
                'z2_enc_activation_hidden': None,
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200]*3,
                'z1_dec_activation_hidden': None,
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200]*3,
                'x_dec_activation_hidden': None,
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v4':{
                'z1_enc_dim':[200],
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200],
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200],
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200],
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v5':{
                'z1_enc_dim':[200]*2,
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200]*2,
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200]*2,
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200]*2,
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v6':{
                'z1_enc_dim':[200]*3,
                'z1_enc_activation_hidden': 'relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200]*3,
                'z2_enc_activation_hidden': 'relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200]*3,
                'z1_dec_activation_hidden': 'relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200]*3,
                'x_dec_activation_hidden': 'relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v7':{
                'z1_enc_dim':[200]*2,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200]*2,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200]*2,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200]*2,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v8':{
                'z1_enc_dim':[200]*3,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200]*3,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200]*3,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200]*3,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            'v9':{
                'z1_enc_dim':[200]*3,
                'z1_enc_activation_hidden': 'leaky-relu',
                'z1_enc_p_dropout': None,
                'z2_enc_dim':[200]*3,
                'z2_enc_activation_hidden': 'leaky-relu',
                'z2_enc_p_dropout': None,
                'z1_dec_dim':[200]*3,
                'z1_dec_activation_hidden': 'leaky-relu',
                'z1_dec_p_dropout': None,
                'x_dec_dim':[200]*3,
                'x_dec_activation_hidden': 'leaky-relu',
                'x_dec_activation_output': None,
                'x_dec_p_dropout': None,
                'z_dim':50,
                'beta':0.5,
                'alpha':1.0, 
                'mmd_dim':500, 
                'mmd_gamma': 1.0
            },
            },
}
